"""
statues_data.py
بيانات الـ 30 تمثال: الاسم، الجنس، والـ prompt الخاص بتوليد الـ 3D.
"""

STATUES = {
    "1":  {"name": "تمثال للملك تحتمس الأول مع آمون رع والملكة إعح", "gender": "male"},
    "2":  {"name": "تمثال حجرى ضخم للملك رمسيس الثاني", "gender": "male"},
    "3":  {"name": "لوحة خشبية ملونة لسيدة تدعى نس-خونسو", "gender": "female"},
    "4":  {"name": "تمثال باك-إن-خونسو الثالث", "gender": "male"},
    "5":  {"name": "لوحة لشخص يدعى ون-نفر", "gender": "male"},
    "6":  {"name": "تمثال كتلة لشخص يدعى با-نوب-إقر", "gender": "male"},
    "7":  {"name": "صندل لمسحتي", "gender": "male"},
    "8":  {"name": "قناع مومياء لمسحتي", "gender": "male"},
    "9":  {"name": "آنية برونزية لمسحتي", "gender": "male"},
    "10": {"name": "وعاء لمسحتي", "gender": "male"},
    "11": {"name": "محفة الملكة حتب-حرس الأولى", "gender": "female"},
    "12": {"name": "عصا خشبية لمسحتي", "gender": "male"},
    "13": {"name": "قلادة فضية لمسحتي", "gender": "male"},
    "14": {"name": "صولجان واس خشبي لمسحتي", "gender": "male"},
    "15": {"name": "إناء لحفظ الزيوت العطرية لمسحتي", "gender": "male"},
    "16": {"name": "مرآة برونزية لمسحتي", "gender": "female"},
    "17": {"name": "نموذج إناء حس لمسحتي", "gender": "male"},
    "18": {"name": "تمثال صغير من الألباستر لمسحتي", "gender": "male"},
    "19": {"name": "التابوت الخارجي لمسحتي", "gender": "male"},
    "20": {"name": "مسند رأس لمسحتي", "gender": "male"},
    "21": {"name": "صلاية على شكل صقر", "gender": "male"},
    "22": {"name": "تمثال للكاتب دوا-بتاح مع والده", "gender": "male"},
    "23": {"name": "تمثال الكاتب متري", "gender": "male"},
    "24": {"name": "نموذج لخادم يشوى إوزة", "gender": "male"},
    "25": {"name": "نموذج لسيدتين تصنعان الجعة", "gender": "female"},
    "26": {"name": "تمثال للكاتب الملكي رع-حتب", "gender": "male"},
    "27": {"name": "تمثال جالس للملك تحتمس الثالث", "gender": "male"},
    "28": {"name": "تمثال لاشيثي", "gender": "male"},
    "29": {"name": "الجزء العلوي لتمثال الملك تحتمس الرابع", "gender": "male"},
    "30": {"name": "تمثال لاشيثي الثاني", "gender": "male"},
}

STATUES_3D_PROMPT = {
    "1":  "ancient Egyptian pharaoh Thutmose seated stone statue with Amun Ra",
    "2":  "colossal ancient Egyptian stone statue of Ramesses II pharaoh",
    "3":  "ancient Egyptian wooden painted stele panel",
    "4":  "ancient Egyptian standing stone statue male figure",
    "5":  "ancient Egyptian limestone stele with carved relief figures",
    "6":  "ancient Egyptian block statue seated man",
    "7":  "ancient Egyptian sandal leather artifact",
    "8":  "ancient Egyptian golden mummy mask portrait",
    "9":  "ancient Egyptian bronze ceremonial vessel jar",
    "10": "ancient Egyptian ceramic pottery vessel",
    "11": "ancient Egyptian royal carrying chair palanquin",
    "12": "ancient Egyptian carved wooden staff",
    "13": "ancient Egyptian silver necklace jewelry collar",
    "14": "ancient Egyptian was scepter wooden carved",
    "15": "ancient Egyptian alabaster perfume oil jar",
    "16": "ancient Egyptian bronze mirror disc handle",
    "17": "ancient Egyptian model ceramic vessel",
    "18": "ancient Egyptian small alabaster statuette figure",
    "19": "ancient Egyptian painted wooden sarcophagus coffin",
    "20": "ancient Egyptian stone headrest pillow",
    "21": "ancient Egyptian falcon-shaped palette stone carved",
    "22": "ancient Egyptian scribe statue seated with father",
    "23": "ancient Egyptian scribe Metry seated limestone statue",
    "24": "ancient Egyptian servant roasting goose model figurine",
    "25": "ancient Egyptian women brewing beer model figurine",
    "26": "ancient Egyptian royal scribe seated statue",
    "27": "ancient Egyptian pharaoh Thutmose III seated throne statue",
    "28": "ancient Egyptian standing male stone statue",
    "29": "ancient Egyptian pharaoh Thutmose IV upper body statue",
    "30": "ancient Egyptian standing male stone statue figure",
}
